import { StyleSheet } from "@react-pdf/renderer";

export const styles = StyleSheet.create({
  page: {
    padding: 30,
    paddingBottom: 40,
    fontFamily: "Helvetica",
    fontSize: 10,
    lineHeight: 1.3,
  },
  header: {
    marginBottom: 10,
    textAlign: "center",
  },
  logoContainer: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 20,
  },
  logo: {
    width: 55,
    height: 75,
    marginRight: 15,
  },
  headerText: {
    flex: 1,
    textAlign: "center",
  },
  title: {
    fontSize: 16,
    fontWeight: "bold",
    marginBottom: 4,
    color: "#000",
    letterSpacing: 0.5,
  },
  subTitle: {
    fontSize: 14,
    fontWeight: "bold",
    marginBottom: 8,
    color: "#000",
    letterSpacing: 0.3,
  },
  address: {
    fontSize: 10,
    marginBottom: 2,
    color: "#333",
    lineHeight: 1.4,
  },
  website: {
    fontSize: 10,
    marginBottom: 8,
    color: "#333",
    fontWeight: "bold",
  },
  divider: {
    borderBottomWidth: 2,
    borderBottomColor: "#000",
    borderBottomStyle: "solid",
    marginBottom: 20,
    marginTop: 8,
  },
  reportTitle: {
    fontSize: 16,
    fontWeight: "bold",
    marginBottom: 8,
    textAlign: "center",
    color: "#000",
    letterSpacing: 0.5,
  },
  reportSubTitle: {
    fontSize: 14,
    fontWeight: "bold",
    marginBottom: 25,
    textAlign: "center",
    color: "#000",
    letterSpacing: 0.3,
  },
  table: {
    width: "100%",
    marginBottom: 20,
    border: "1.5px solid #000",
  },
  tableHeader: {
    flexDirection: "row",
    backgroundColor: "#e8e8e8",
    borderBottomWidth: 1.5,
    borderBottomColor: "#000",
    borderBottomStyle: "solid",
    minHeight: 40,
    alignItems: "center",
  },
  tableRow: {
    flexDirection: "row",
    borderBottomWidth: 0.5,
    borderBottomColor: "#666",
    borderBottomStyle: "solid",
    minHeight: 40,
    alignItems: "stretch",
  },
  tableColNo: {
    width: "7%",
    fontSize: 10,
    textAlign: "center",
    borderRightWidth: 1,
    borderRightColor: "#000",
    borderRightStyle: "solid",
    padding: 6,
  },
  tableColDate: {
    width: "13%",
    fontSize: 10,
    textAlign: "center",
    borderRightWidth: 1,
    borderRightColor: "#000",
    borderRightStyle: "solid",
    padding: 6,
  },
  tableColSender: {
    width: "25%",
    fontSize: 9,
    textAlign: "left",
    borderRightWidth: 1,
    borderRightColor: "#000",
    borderRightStyle: "solid",
    padding: 6,
  },
  tableColReceiver: {
    width: "20%",
    fontSize: 9,
    textAlign: "center",
    borderRightWidth: 1,
    borderRightColor: "#000",
    borderRightStyle: "solid",
    padding: 6,
  },
  tableColSubject: {
    width: "40%",
    fontSize: 9,
    textAlign: "left",
    padding: 6,
    flexWrap: "wrap",
  },
  tableHeaderText: {
    fontWeight: "bold",
    fontSize: 11,
    textAlign: "center",
  },
  tableHeaderTextLeft: {
    fontWeight: "bold",
    fontSize: 11,
    textAlign: "left",
  },
  tableCellText: {
    fontSize: 9,
    lineHeight: 1.3,
    color: "#000",
    wordWrap: "break-word",
  },
  footer: {
    marginTop: 30,
    fontSize: 12,
    fontWeight: "bold",
    textAlign: "left",
    padding: 10,
    backgroundColor: "#f5f5f5",
    border: "1px solid #ccc",
  },
  pageNumber: {
    position: "absolute",
    fontSize: 9,
    bottom: 20,
    left: 0,
    right: 0,
    textAlign: "center",
    color: "#666",
  },
  monthlyTitle: {
    textAlign: "center",
    marginBottom: 20,
    fontSize: 14,
    fontWeight: "bold",
  },
});
